/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard.index'
import { Route as DashboardUsersIndexRouteImport } from './routes/_dashboard.users.index'
import { Route as DashboardSchemasIndexRouteImport } from './routes/_dashboard.schemas.index'
import { Route as DashboardUsersIdRouteImport } from './routes/_dashboard.users.$id'
import { Route as DashboardSchemasTypeRouteImport } from './routes/_dashboard.schemas.$type'
import { Route as DashboardItemsItemTypeIndexRouteImport } from './routes/_dashboard.items.$itemType.index'
import { Route as DashboardUsersIdDeleteRouteImport } from './routes/_dashboard.users.$id.delete'
import { Route as DashboardItemsItemTypeSeedRouteImport } from './routes/_dashboard.items.$itemType.seed'
import { Route as DashboardItemsItemTypeIdRouteImport } from './routes/_dashboard.items.$itemType.$id'
import { Route as DashboardItemsItemTypeIdDeleteRouteImport } from './routes/_dashboard.items.$itemType.$id.delete'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersIndexRoute = DashboardUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSchemasIndexRoute = DashboardSchemasIndexRouteImport.update({
  id: '/schemas/',
  path: '/schemas/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersIdRoute = DashboardUsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSchemasTypeRoute = DashboardSchemasTypeRouteImport.update({
  id: '/schemas/$type',
  path: '/schemas/$type',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardItemsItemTypeIndexRoute =
  DashboardItemsItemTypeIndexRouteImport.update({
    id: '/items/$itemType/',
    path: '/items/$itemType/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardUsersIdDeleteRoute = DashboardUsersIdDeleteRouteImport.update({
  id: '/delete',
  path: '/delete',
  getParentRoute: () => DashboardUsersIdRoute,
} as any)
const DashboardItemsItemTypeSeedRoute =
  DashboardItemsItemTypeSeedRouteImport.update({
    id: '/items/$itemType/seed',
    path: '/items/$itemType/seed',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardItemsItemTypeIdRoute =
  DashboardItemsItemTypeIdRouteImport.update({
    id: '/items/$itemType/$id',
    path: '/items/$itemType/$id',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardItemsItemTypeIdDeleteRoute =
  DashboardItemsItemTypeIdDeleteRouteImport.update({
    id: '/delete',
    path: '/delete',
    getParentRoute: () => DashboardItemsItemTypeIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/login': typeof LoginRoute
  '/schemas/$type': typeof DashboardSchemasTypeRoute
  '/users/$id': typeof DashboardUsersIdRouteWithChildren
  '/schemas/': typeof DashboardSchemasIndexRoute
  '/users/': typeof DashboardUsersIndexRoute
  '/items/$itemType/$id': typeof DashboardItemsItemTypeIdRouteWithChildren
  '/items/$itemType/seed': typeof DashboardItemsItemTypeSeedRoute
  '/users/$id/delete': typeof DashboardUsersIdDeleteRoute
  '/items/$itemType/': typeof DashboardItemsItemTypeIndexRoute
  '/items/$itemType/$id/delete': typeof DashboardItemsItemTypeIdDeleteRoute
}
export interface FileRoutesByTo {
  '/access-denied': typeof AccessDeniedRoute
  '/login': typeof LoginRoute
  '/': typeof DashboardIndexRoute
  '/schemas/$type': typeof DashboardSchemasTypeRoute
  '/users/$id': typeof DashboardUsersIdRouteWithChildren
  '/schemas': typeof DashboardSchemasIndexRoute
  '/users': typeof DashboardUsersIndexRoute
  '/items/$itemType/$id': typeof DashboardItemsItemTypeIdRouteWithChildren
  '/items/$itemType/seed': typeof DashboardItemsItemTypeSeedRoute
  '/users/$id/delete': typeof DashboardUsersIdDeleteRoute
  '/items/$itemType': typeof DashboardItemsItemTypeIndexRoute
  '/items/$itemType/$id/delete': typeof DashboardItemsItemTypeIdDeleteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/access-denied': typeof AccessDeniedRoute
  '/login': typeof LoginRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/schemas/$type': typeof DashboardSchemasTypeRoute
  '/_dashboard/users/$id': typeof DashboardUsersIdRouteWithChildren
  '/_dashboard/schemas/': typeof DashboardSchemasIndexRoute
  '/_dashboard/users/': typeof DashboardUsersIndexRoute
  '/_dashboard/items/$itemType/$id': typeof DashboardItemsItemTypeIdRouteWithChildren
  '/_dashboard/items/$itemType/seed': typeof DashboardItemsItemTypeSeedRoute
  '/_dashboard/users/$id/delete': typeof DashboardUsersIdDeleteRoute
  '/_dashboard/items/$itemType/': typeof DashboardItemsItemTypeIndexRoute
  '/_dashboard/items/$itemType/$id/delete': typeof DashboardItemsItemTypeIdDeleteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-denied'
    | '/login'
    | '/schemas/$type'
    | '/users/$id'
    | '/schemas/'
    | '/users/'
    | '/items/$itemType/$id'
    | '/items/$itemType/seed'
    | '/users/$id/delete'
    | '/items/$itemType/'
    | '/items/$itemType/$id/delete'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/access-denied'
    | '/login'
    | '/'
    | '/schemas/$type'
    | '/users/$id'
    | '/schemas'
    | '/users'
    | '/items/$itemType/$id'
    | '/items/$itemType/seed'
    | '/users/$id/delete'
    | '/items/$itemType'
    | '/items/$itemType/$id/delete'
  id:
    | '__root__'
    | '/_dashboard'
    | '/access-denied'
    | '/login'
    | '/_dashboard/'
    | '/_dashboard/schemas/$type'
    | '/_dashboard/users/$id'
    | '/_dashboard/schemas/'
    | '/_dashboard/users/'
    | '/_dashboard/items/$itemType/$id'
    | '/_dashboard/items/$itemType/seed'
    | '/_dashboard/users/$id/delete'
    | '/_dashboard/items/$itemType/'
    | '/_dashboard/items/$itemType/$id/delete'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  AccessDeniedRoute: typeof AccessDeniedRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/users/': {
      id: '/_dashboard/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof DashboardUsersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/schemas/': {
      id: '/_dashboard/schemas/'
      path: '/schemas'
      fullPath: '/schemas/'
      preLoaderRoute: typeof DashboardSchemasIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/users/$id': {
      id: '/_dashboard/users/$id'
      path: '/users/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof DashboardUsersIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/schemas/$type': {
      id: '/_dashboard/schemas/$type'
      path: '/schemas/$type'
      fullPath: '/schemas/$type'
      preLoaderRoute: typeof DashboardSchemasTypeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/items/$itemType/': {
      id: '/_dashboard/items/$itemType/'
      path: '/items/$itemType'
      fullPath: '/items/$itemType/'
      preLoaderRoute: typeof DashboardItemsItemTypeIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/users/$id/delete': {
      id: '/_dashboard/users/$id/delete'
      path: '/delete'
      fullPath: '/users/$id/delete'
      preLoaderRoute: typeof DashboardUsersIdDeleteRouteImport
      parentRoute: typeof DashboardUsersIdRoute
    }
    '/_dashboard/items/$itemType/seed': {
      id: '/_dashboard/items/$itemType/seed'
      path: '/items/$itemType/seed'
      fullPath: '/items/$itemType/seed'
      preLoaderRoute: typeof DashboardItemsItemTypeSeedRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/items/$itemType/$id': {
      id: '/_dashboard/items/$itemType/$id'
      path: '/items/$itemType/$id'
      fullPath: '/items/$itemType/$id'
      preLoaderRoute: typeof DashboardItemsItemTypeIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/items/$itemType/$id/delete': {
      id: '/_dashboard/items/$itemType/$id/delete'
      path: '/delete'
      fullPath: '/items/$itemType/$id/delete'
      preLoaderRoute: typeof DashboardItemsItemTypeIdDeleteRouteImport
      parentRoute: typeof DashboardItemsItemTypeIdRoute
    }
  }
}

interface DashboardUsersIdRouteChildren {
  DashboardUsersIdDeleteRoute: typeof DashboardUsersIdDeleteRoute
}

const DashboardUsersIdRouteChildren: DashboardUsersIdRouteChildren = {
  DashboardUsersIdDeleteRoute: DashboardUsersIdDeleteRoute,
}

const DashboardUsersIdRouteWithChildren =
  DashboardUsersIdRoute._addFileChildren(DashboardUsersIdRouteChildren)

interface DashboardItemsItemTypeIdRouteChildren {
  DashboardItemsItemTypeIdDeleteRoute: typeof DashboardItemsItemTypeIdDeleteRoute
}

const DashboardItemsItemTypeIdRouteChildren: DashboardItemsItemTypeIdRouteChildren =
  {
    DashboardItemsItemTypeIdDeleteRoute: DashboardItemsItemTypeIdDeleteRoute,
  }

const DashboardItemsItemTypeIdRouteWithChildren =
  DashboardItemsItemTypeIdRoute._addFileChildren(
    DashboardItemsItemTypeIdRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardSchemasTypeRoute: typeof DashboardSchemasTypeRoute
  DashboardUsersIdRoute: typeof DashboardUsersIdRouteWithChildren
  DashboardSchemasIndexRoute: typeof DashboardSchemasIndexRoute
  DashboardUsersIndexRoute: typeof DashboardUsersIndexRoute
  DashboardItemsItemTypeIdRoute: typeof DashboardItemsItemTypeIdRouteWithChildren
  DashboardItemsItemTypeSeedRoute: typeof DashboardItemsItemTypeSeedRoute
  DashboardItemsItemTypeIndexRoute: typeof DashboardItemsItemTypeIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardSchemasTypeRoute: DashboardSchemasTypeRoute,
  DashboardUsersIdRoute: DashboardUsersIdRouteWithChildren,
  DashboardSchemasIndexRoute: DashboardSchemasIndexRoute,
  DashboardUsersIndexRoute: DashboardUsersIndexRoute,
  DashboardItemsItemTypeIdRoute: DashboardItemsItemTypeIdRouteWithChildren,
  DashboardItemsItemTypeSeedRoute: DashboardItemsItemTypeSeedRoute,
  DashboardItemsItemTypeIndexRoute: DashboardItemsItemTypeIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  AccessDeniedRoute: AccessDeniedRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
