options:
  prev_tag: "versio-prev"

projects:
  - name: "client"
    id: 1
    root: "apps/client"
    changelog: "CHANGELOG.md"
    tag_prefix: "client"
    version:
      tags:
        default: "1.0.0"

  - name: "admin"
    id: 2
    root: "apps/admin"
    changelog: "CHANGELOG.md"
    tag_prefix: "admin"
    version:
      tags:
        default: "1.0.0"

  - name: "api"
    id: 3
    root: "apps/api"
    changelog: "CHANGELOG.md"
    tag_prefix: "api"
    version:
      tags:
        default: "1.0.0"

sizes:
  use_angular: true
  fail: ["*"]
