services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    volumes:
      - ./src:/app/src
      - ./index.html:/app/index.html
      - ./vite.config.ts:/app/vite.config.ts
      - ./tsconfig.json:/app/tsconfig.json
      - /app/node_modules
    depends_on:
      api:
        condition: service_started
    networks:
      - default
