name: Release Please

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Run release-please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}

      - name: Show release outputs
        if: steps.release.outputs.releases_created == 'true'
        run: |
          echo "🚀 Releases created!"
          echo "Tags will be created automatically and trigger the release workflow"
